import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FireworksBackground } from "./fireworks";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-500 max-h-[200px]">{children}</body>
    </html>
  );
}
